# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('accreditations', models.JSONField(default=list)),
                ('established_year', models.IntegerField(default=1995)),
                ('beds_count', models.IntegerField(default=1200)),
                ('image_url', models.CharField(max_length=500)),
                ('overview', models.TextField()),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(default='activity', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('treatment_name', models.CharField(max_length=200)),
                ('country_preference', models.CharField(default='India', max_length=100)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_age', models.IntegerField(default=45)),
                ('patient_gender', models.CharField(default='male', max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('medical_condition_summary', models.TextField()),
                ('medical_reports_json', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('enquiry_received', 'Enquiry Received'), ('doctor_reviewing', 'Doctor Reviewing Medical Records'), ('quote_issued', 'Treatment Plan & Quote Issued'), ('consultation_scheduled', 'Video Consultation Scheduled'), ('visa_travel_arranged', 'Medical Visa & Travel Arranged')], default='enquiry_received', max_length=30)),
                ('doctor_opinion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_detail', to='core_bookings.booking')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='medical_tourism.medicalhospital')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=200)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=2, default=4500.0, max_digits=10)),
                ('us_benchmark_cost_usd', models.DecimalField(decimal_places=2, default=35000.0, max_digits=10)),
                ('hospital_stay_days', models.IntegerField(default=4)),
                ('total_stay_days', models.IntegerField(default=10)),
                ('success_rate', models.CharField(default='99.2%', max_length=20)),
                ('inclusions', models.JSONField(default=list)),
                ('overview', models.TextField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='medical_tourism.medicalhospital')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='medical_tourism.medicalspecialty')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhospital',
            name='specialties',
            field=models.ManyToManyField(related_name='hospitals', to='medical_tourism.medicalspecialty'),
        ),
    ]
