# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('flag_emoji', models.CharField(default='🌍', max_length=10)),
                ('processing_time_days', models.CharField(default='3 to 5 business days', max_length=50)),
                ('starting_price', models.DecimalField(decimal_places=2, default=99.0, max_digits=8)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements_checklist', models.JSONField(default=list)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('validity_duration', models.CharField(default='60 days from issuance', max_length=50)),
                ('stay_duration', models.CharField(default='30 days', max_length=50)),
                ('entry_type', models.CharField(default='Single Entry', max_length=50)),
                ('government_fee', models.DecimalField(decimal_places=2, default=65.0, max_digits=8)),
                ('service_fee', models.DecimalField(decimal_places=2, default=34.0, max_digits=8)),
                ('total_fee', models.DecimalField(decimal_places=2, default=99.0, max_digits=8)),
                ('express_available', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='visa.visacountry')),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Application Submitted'), ('documents_verified', 'Documents Verified'), ('embassy_processing', 'Under Processing at Embassy'), ('approved', 'Visa Approved / Issued'), ('rejected', 'Action Required / Rejected')], default='submitted', max_length=30)),
                ('applicant_full_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='United States', max_length=100)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('passport_copy_url', models.CharField(blank=True, max_length=500, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('supporting_docs_json', models.JSONField(default=list)),
                ('embassy_remarks', models.TextField(blank=True, null=True)),
                ('issued_visa_doc_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_detail', to='core_bookings.booking')),
                ('visa_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='visa.visacountry')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='visa.visatype')),
            ],
        ),
    ]
