# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(choices=[('makkah', 'Makkah'), ('madinah', 'Madinah')], max_length=20)),
                ('star_rating', models.IntegerField(default=5)),
                ('distance_from_haram', models.CharField(default='0 meters (Facing Haram)', max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('vip_luxury', 'VIP 5-Star Luxury (Haram Front)'), ('classic_premium', 'Classic 4-Star Premium'), ('economy_saver', 'Economy Saver'), ('ramadan_special', 'Ramadan Special Package')], default='vip_luxury', max_length=50)),
                ('duration_days', models.IntegerField(default=14)),
                ('makkah_nights', models.IntegerField(default=7)),
                ('madinah_nights', models.IntegerField(default=7)),
                ('price_quad', models.DecimalField(decimal_places=2, default=1499.0, max_digits=10)),
                ('price_triple', models.DecimalField(decimal_places=2, default=1699.0, max_digits=10)),
                ('price_double', models.DecimalField(decimal_places=2, default=1999.0, max_digits=10)),
                ('main_image', models.CharField(max_length=500)),
                ('gallery_images', models.JSONField(default=list)),
                ('overview', models.TextField()),
                ('visa_included', models.BooleanField(default=True)),
                ('flights_included', models.BooleanField(default=True)),
                ('transfers_included', models.BooleanField(default=True)),
                ('ziyarat_included', models.BooleanField(default=True)),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('itinerary_summary', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=True)),
                ('madinah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madinah_packages', to='umrah.umrahhotel')),
                ('makkah_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makkah_packages', to='umrah.umrahhotel')),
            ],
        ),
        migrations.CreateModel(
            name='UmrahBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('pilgrims_count', models.IntegerField(default=2)),
                ('room_type', models.CharField(default='Double Sharing', max_length=50)),
                ('need_visa_assistance', models.BooleanField(default=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_detail', to='core_bookings.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='umrah.umrahpackage')),
            ],
        ),
    ]
