# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.6, max_digits=3)),
                ('total_reviews', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(choices=[('ac_sleeper', 'AC Sleeper (2+1)'), ('volvo_multi_axle', 'Volvo Multi-Axle AC Semi-Sleeper (2+2)'), ('scania_ac', 'Scania AC Executive (2+2)'), ('non_ac_sleeper', 'Non-AC Sleeper (2+1)')], default='volvo_multi_axle', max_length=50)),
                ('bus_name', models.CharField(default='Volvo Multi-Axle Luxury AC', max_length=150)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.CharField(help_text='e.g. 09:00 PM', max_length=10)),
                ('arrival_time', models.CharField(help_text='e.g. 06:30 AM', max_length=10)),
                ('duration', models.CharField(help_text='e.g. 9h 30m', max_length=50)),
                ('fare_seater', models.DecimalField(decimal_places=2, default=35.0, max_digits=8)),
                ('fare_sleeper', models.DecimalField(decimal_places=2, default=55.0, max_digits=8)),
                ('boarding_points', models.JSONField(default=list)),
                ('dropping_points', models.JSONField(default=list)),
                ('total_seats', models.IntegerField(default=36)),
                ('available_seats_count', models.IntegerField(default=22)),
                ('amenities', models.JSONField(default=list)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.busoperator')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('deck', models.CharField(choices=[('lower', 'Lower Deck'), ('upper', 'Upper Deck')], default='lower', max_length=10)),
                ('seat_type', models.CharField(choices=[('seater', 'Seater'), ('sleeper', 'Sleeper Bed')], default='seater', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=35.0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_ladies_only', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bustrip')),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_seats', models.JSONField(default=list)),
                ('passengers', models.JSONField(default=list)),
                ('boarding_point', models.CharField(max_length=255)),
                ('dropping_point', models.CharField(max_length=255)),
                ('m_ticket_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_detail', to='core_bookings.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='buses.bustrip')),
            ],
        ),
    ]
