# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('booking_type', models.CharField(choices=[('flight', 'Flight Booking'), ('hotel', 'Hotel Booking'), ('bus', 'Bus Booking'), ('visa', 'Visa Application'), ('insurance', 'Travel Insurance Policy'), ('holiday', 'Holiday Package Tour'), ('umrah', 'Umrah Pilgrimage Package'), ('medical_tourism', 'Medical Tourism Package'), ('europamundo', 'Europamundo Tour Circuit'), ('utility', 'Travel Utility (eSIM/Forex/Lounge)'), ('mixed', 'Unified Multi-Item Booking')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing / Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='confirmed', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('title', models.CharField(default='Travel Booking', max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
