# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=5, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_time', models.CharField(help_text='e.g. 08:30 AM', max_length=10)),
                ('arrival_time', models.CharField(help_text='e.g. 02:45 PM', max_length=10)),
                ('duration', models.CharField(help_text='e.g. 6h 15m', max_length=50)),
                ('stops', models.IntegerField(default=0, help_text='0 for Direct/Non-stop, 1, 2')),
                ('stop_details', models.CharField(blank=True, help_text='e.g. 1h 45m in Doha (DOH)', max_length=255, null=True)),
                ('price_economy', models.DecimalField(decimal_places=2, default=350.0, max_digits=10)),
                ('price_premium', models.DecimalField(decimal_places=2, default=580.0, max_digits=10)),
                ('price_business', models.DecimalField(decimal_places=2, default=1250.0, max_digits=10)),
                ('price_first', models.DecimalField(decimal_places=2, default=2400.0, max_digits=10)),
                ('baggage_checkin', models.CharField(default='30 kg', max_length=50)),
                ('baggage_cabin', models.CharField(default='7 kg', max_length=50)),
                ('refundable', models.BooleanField(default=True)),
                ('aircraft_type', models.CharField(default='Boeing 777-300ER', max_length=100)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='flights.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(default='economy', max_length=30)),
                ('passengers_json', models.JSONField(default=list)),
                ('selected_seats', models.CharField(blank=True, max_length=100, null=True)),
                ('e_ticket_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('meal_preference', models.CharField(default='Standard', max_length=100)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_detail', to='core_bookings.booking')),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flightschedule')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('extra_legroom', 'Extra Legroom'), ('business', 'Business')], default='economy', max_length=20)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flightschedule')),
            ],
        ),
    ]
