# Generated by Django 6.1 on 2026-08-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='has_entertainment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='has_meals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='has_usb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='seat_layout',
            field=models.CharField(default='3-3', help_text='e.g. 3-3, 2-4-2, 3-3-3', max_length=20),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='wifi_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
