# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(default='Asia', max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('tagline', models.CharField(default='Tropical Paradise & Ancient Temples', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_days', models.IntegerField(default=6)),
                ('duration_nights', models.IntegerField(default=5)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=799.0, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=1099.0, max_digits=10)),
                ('main_image', models.CharField(max_length=500)),
                ('gallery_images', models.JSONField(default=list)),
                ('overview', models.TextField()),
                ('inclusions', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('hotel_rating', models.IntegerField(default=4)),
                ('meals_included', models.CharField(default='Breakfast Included', max_length=100)),
                ('flights_included', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='holidays.holidaydestination')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('travelers_count', models.IntegerField(default=2)),
                ('room_sharing', models.CharField(default='Twin Sharing', max_length=50)),
                ('custom_requests', models.TextField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_detail', to='core_bookings.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='holidays.holidaypackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meals_today', models.CharField(default='Dinner', max_length=100)),
                ('activities', models.JSONField(default=list)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='holidays.holidaypackage')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
