# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EuropamundoTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('countries_covered', models.JSONField(default=list)),
                ('cities_visited', models.CharField(default='Madrid, Toledo, Lisbon, Porto, Salamanca', max_length=255)),
                ('duration_days', models.IntegerField(default=10)),
                ('duration_nights', models.IntegerField(default=9)),
                ('price_eur', models.DecimalField(decimal_places=2, default=1350.0, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, default=1480.0, max_digits=10)),
                ('bus_type', models.CharField(default='Luxury Panoramic Coach with Free Wi-Fi', max_length=100)),
                ('hotel_category', models.CharField(default='4-Star Comfort Hotels', max_length=50)),
                ('audio_languages', models.JSONField(default=list)),
                ('guaranteed_departures', models.BooleanField(default=True)),
                ('main_image', models.CharField(max_length=500)),
                ('gallery_images', models.JSONField(default=list)),
                ('overview', models.TextField()),
                ('inclusions', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('available_seats', models.IntegerField(default=24)),
                ('status', models.CharField(default='Guaranteed Departure', max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='europamundo.europamundotour')),
            ],
        ),
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=1)),
                ('city_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('highlight_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('km_distance', models.IntegerField(default=220)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='europamundo.europamundotour')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
