# Generated by Django 6.1 on 2026-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=5)),
                ('airport_name', models.CharField(max_length=150)),
                ('terminal', models.CharField(default='Terminal 3', max_length=50)),
                ('lounge_name', models.CharField(max_length=150)),
                ('operating_hours', models.CharField(default='24 Hours Daily', max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, default=38.0, max_digits=8)),
                ('amenities', models.JSONField(default=list)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsimPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_or_region', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='GLOBAL', max_length=10)),
                ('data_allowance', models.CharField(max_length=50)),
                ('validity_days', models.IntegerField(default=15)),
                ('price_usd', models.DecimalField(decimal_places=2, default=14.99, max_digits=8)),
                ('network_speed', models.CharField(default='5G / 4G LTE', max_length=50)),
                ('hotspot_tethering', models.BooleanField(default=True)),
                ('instant_qr_delivery', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=5, unique=True)),
                ('currency_name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(default='💱', max_length=10)),
                ('buy_rate_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('forex_card_available', models.BooleanField(default=True)),
                ('currency_notes_available', models.BooleanField(default=True)),
            ],
        ),
    ]
