# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(default='wifi', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('star_rating', models.IntegerField(default=5)),
                ('guest_rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('reviews_count', models.IntegerField(default=340)),
                ('price_per_night_start', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('main_image', models.CharField(blank=True, max_length=500, null=True)),
                ('images_gallery', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('free_cancellation', models.BooleanField(default=True)),
                ('breakfast_included', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelamenity')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150)),
                ('bed_type', models.CharField(default='1 Extra-large double bed', max_length=100)),
                ('max_guests', models.IntegerField(default=2)),
                ('room_size_sqm', models.IntegerField(default=38)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=180.0, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('features_json', models.JSONField(default=list)),
                ('available_units', models.IntegerField(default=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.IntegerField(default=1)),
                ('rooms_count', models.IntegerField(default=1)),
                ('guests_count', models.IntegerField(default=2)),
                ('guest_names', models.JSONField(default=list)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_detail', to='core_bookings.booking')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='hotels.hotelroom')),
            ],
        ),
    ]
