# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('region', models.CharField(choices=[('worldwide', 'Worldwide (Including USA & Canada)'), ('worldwide_ex_us', 'Worldwide (Excluding USA & Canada)'), ('schengen', 'Schengen Countries Only'), ('asia', 'Asia Pacific')], default='worldwide', max_length=50)),
                ('medical_coverage_amount', models.CharField(default='$500,000', max_length=50)),
                ('trip_cancellation_amount', models.CharField(default='$10,000', max_length=50)),
                ('baggage_loss_amount', models.CharField(default='$2,500', max_length=50)),
                ('flight_delay_amount', models.CharField(default='$1,000', max_length=50)),
                ('covid19_covered', models.BooleanField(default=True)),
                ('cashless_hospitalization', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=4.5, max_digits=8)),
                ('flat_price', models.DecimalField(decimal_places=2, default=39.0, max_digits=8)),
                ('benefits_list', models.JSONField(default=list)),
                ('policy_wording_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_settlement_ratio', models.CharField(default='98.7%', max_length=20)),
                ('emergency_assistance_phone', models.CharField(default='+1 (800) 555-0199', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('insured_persons', models.JSONField(default=list)),
                ('destination_country', models.CharField(default='Worldwide', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField(default=7)),
                ('policy_pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_detail', to='core_bookings.booking')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.insuranceplan')),
            ],
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insuranceprovider'),
        ),
    ]
