# Generated by Django 6.1 on 2026-08-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off (%)'), ('flat', 'Flat Amount Off ($)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('applicable_module', models.CharField(choices=[('all', 'All Travel Modules'), ('flight', 'Flights Only'), ('hotel', 'Hotels Only'), ('holiday', 'Holiday Packages Only'), ('visa', 'Visa Only'), ('insurance', 'Insurance Only')], default='all', max_length=20)),
                ('bank_partner', models.CharField(blank=True, help_text='e.g. HDFC, Chase, Amex, Citi', max_length=100, null=True)),
                ('badge_text', models.CharField(default='INSTANT DISCOUNT', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=255)),
                ('category', models.CharField(default='flight', max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('cta_link', models.CharField(default='/flights', max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='offers.couponcode')),
            ],
        ),
    ]
